name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Autograder
      id: autograder
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Autograder
        setup-command: sudo -H pip3 install pytest
        command: pytest -s
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        AUTOGRADER_RESULTS: "${{steps.autograder.outputs.result}}"
      with:
        runners: autograder
